import { db } from '@/db';
import { movies } from '@/db/schema';

async function main() {
    const sampleMovies = [
        {
            tmdbId: 278,
            title: 'The Shawshank Redemption',
            overview: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency. A powerful story of hope and friendship that transcends the brutal confines of prison life.',
            releaseDate: '1994-09-23',
            posterPath: '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
            backdropPath: '/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
            rating: 8.7,
            genres: JSON.stringify(['drama']),
            director: 'Frank Darabont',
            cast: JSON.stringify(['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler']),
            runtime: 142,
            voteCount: 12450,
            popularity: 125.8,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=6hB3S9bIaco']),
            aiTags: JSON.stringify(['uplifting', 'thought-provoking', 'heartwarming']),
            underrated: false,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            tmdbId: 155,
            title: 'The Dark Knight',
            overview: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice. A masterful exploration of heroism and villainy.',
            releaseDate: '2008-07-18',
            posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            backdropPath: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
            rating: 9.0,
            genres: JSON.stringify(['action', 'thriller']),
            director: 'Christopher Nolan',
            cast: JSON.stringify(['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine']),
            runtime: 152,
            voteCount: 14820,
            popularity: 148.5,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=EXeTwQWrcwY']),
            aiTags: JSON.stringify(['thrilling', 'dark', 'intense', 'cerebral']),
            underrated: false,
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            tmdbId: 27205,
            title: 'Inception',
            overview: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O. A mind-bending journey through layers of reality and dreams.',
            releaseDate: '2010-07-16',
            posterPath: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
            backdropPath: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
            rating: 8.8,
            genres: JSON.stringify(['sci-fi', 'thriller']),
            director: 'Christopher Nolan',
            cast: JSON.stringify(['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Ellen Page', 'Tom Hardy']),
            runtime: 148,
            voteCount: 13560,
            popularity: 142.3,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=YoHD9XEInc0']),
            aiTags: JSON.stringify(['cerebral', 'thought-provoking', 'thrilling', 'intense']),
            underrated: false,
            createdAt: new Date('2024-01-17').toISOString(),
            updatedAt: new Date('2024-01-17').toISOString(),
        },
        {
            tmdbId: 680,
            title: 'Pulp Fiction',
            overview: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption. A groundbreaking narrative structure that revolutionized modern cinema.',
            releaseDate: '1994-10-14',
            posterPath: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
            backdropPath: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
            rating: 8.9,
            genres: JSON.stringify(['crime', 'drama']),
            director: 'Quentin Tarantino',
            cast: JSON.stringify(['John Travolta', 'Uma Thurman', 'Samuel L. Jackson', 'Bruce Willis']),
            runtime: 154,
            voteCount: 13890,
            popularity: 138.7,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=s7EdQ4FqbhY']),
            aiTags: JSON.stringify(['dark', 'intense', 'thrilling', 'cerebral']),
            underrated: false,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        {
            tmdbId: 13,
            title: 'Forrest Gump',
            overview: 'The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man with an IQ of 75. A heartwarming journey through decades of American history.',
            releaseDate: '1994-07-06',
            posterPath: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
            backdropPath: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
            rating: 8.8,
            genres: JSON.stringify(['drama', 'romance']),
            director: 'Robert Zemeckis',
            cast: JSON.stringify(['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field']),
            runtime: 142,
            voteCount: 12980,
            popularity: 135.4,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=bLvqoHBptjg']),
            aiTags: JSON.stringify(['uplifting', 'heartwarming', 'thought-provoking']),
            underrated: false,
            createdAt: new Date('2024-01-19').toISOString(),
            updatedAt: new Date('2024-01-19').toISOString(),
        },
        {
            tmdbId: 603,
            title: 'The Matrix',
            overview: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers. A revolutionary sci-fi action film that questions the nature of reality.',
            releaseDate: '1999-03-31',
            posterPath: '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
            backdropPath: '/fNG7i7RqMErkcqhohV2a6cV1Ehy.jpg',
            rating: 8.7,
            genres: JSON.stringify(['sci-fi', 'action']),
            director: 'Wachowski Brothers',
            cast: JSON.stringify(['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving']),
            runtime: 136,
            voteCount: 12340,
            popularity: 128.9,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=vKQi3bBA1y8']),
            aiTags: JSON.stringify(['cerebral', 'thrilling', 'intense', 'thought-provoking']),
            underrated: false,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            tmdbId: 157336,
            title: 'Interstellar',
            overview: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival. An epic journey across time and space that explores love, sacrifice, and the survival of mankind.',
            releaseDate: '2014-11-07',
            posterPath: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
            backdropPath: '/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
            rating: 8.6,
            genres: JSON.stringify(['sci-fi', 'drama']),
            director: 'Christopher Nolan',
            cast: JSON.stringify(['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine']),
            runtime: 169,
            voteCount: 11750,
            popularity: 132.1,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=zSWdZVtXT7E']),
            aiTags: JSON.stringify(['cerebral', 'thought-provoking', 'uplifting', 'intense']),
            underrated: false,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            tmdbId: 238,
            title: 'The Godfather',
            overview: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son. An epic tale of family, power, and the American Dream corrupted.',
            releaseDate: '1972-03-24',
            posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            backdropPath: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
            rating: 9.2,
            genres: JSON.stringify(['crime', 'drama']),
            director: 'Francis Ford Coppola',
            cast: JSON.stringify(['Marlon Brando', 'Al Pacino', 'James Caan', 'Robert Duvall']),
            runtime: 175,
            voteCount: 14950,
            popularity: 145.6,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=sY1S34973zA']),
            aiTags: JSON.stringify(['dark', 'intense', 'cerebral', 'thought-provoking']),
            underrated: false,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            tmdbId: 496243,
            title: 'Parasite',
            overview: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan. A darkly comedic thriller that dissects modern society.',
            releaseDate: '2019-05-30',
            posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
            backdropPath: '/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
            rating: 8.6,
            genres: JSON.stringify(['thriller', 'drama']),
            director: 'Bong Joon-ho',
            cast: JSON.stringify(['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik']),
            runtime: 132,
            voteCount: 11230,
            popularity: 126.7,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=5xH0HfJHsaY']),
            aiTags: JSON.stringify(['thrilling', 'dark', 'thought-provoking', 'intense']),
            underrated: false,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            tmdbId: 129,
            title: 'Spirited Away',
            overview: 'During her family\'s move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits. A magical journey of self-discovery and courage in a fantastical realm.',
            releaseDate: '2001-07-20',
            posterPath: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
            backdropPath: '/Ab8mkHmkYADjU7wQiOkia9BzGvS.jpg',
            rating: 8.6,
            genres: JSON.stringify(['animation', 'fantasy']),
            director: 'Hayao Miyazaki',
            cast: JSON.stringify(['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Bunta Sugawara']),
            runtime: 125,
            voteCount: 10890,
            popularity: 119.4,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=ByXuk9QqQkk']),
            aiTags: JSON.stringify(['heartwarming', 'uplifting', 'thought-provoking']),
            underrated: false,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            tmdbId: 274,
            title: 'The Silence of the Lambs',
            overview: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer. A psychological thriller that defined the genre.',
            releaseDate: '1991-02-14',
            posterPath: '/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg',
            backdropPath: '/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg',
            rating: 8.6,
            genres: JSON.stringify(['horror', 'thriller']),
            director: 'Jonathan Demme',
            cast: JSON.stringify(['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn', 'Ted Levine']),
            runtime: 118,
            voteCount: 11450,
            popularity: 122.8,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=W6Mm8Sbe__o']),
            aiTags: JSON.stringify(['thrilling', 'dark', 'suspenseful', 'intense']),
            underrated: false,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            tmdbId: 419430,
            title: 'Get Out',
            overview: 'A young African-American visits his white girlfriend\'s parents for the weekend, where his simmering uneasiness about their reception of him eventually reaches a boiling point. A groundbreaking social thriller.',
            releaseDate: '2017-02-24',
            posterPath: '/tFXcEccSQMf3lfhfXKSU9iRBpa3.jpg',
            backdropPath: '/mDc63BXnHE6uy26sPntYpRWGY7s.jpg',
            rating: 7.7,
            genres: JSON.stringify(['horror', 'thriller']),
            director: 'Jordan Peele',
            cast: JSON.stringify(['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford', 'Catherine Keener']),
            runtime: 104,
            voteCount: 9870,
            popularity: 98.5,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=DzfpyUB60YY']),
            aiTags: JSON.stringify(['thrilling', 'suspenseful', 'thought-provoking', 'dark']),
            underrated: false,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            tmdbId: 76341,
            title: 'Mad Max: Fury Road',
            overview: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners and a drifter. A non-stop adrenaline-fueled chase.',
            releaseDate: '2015-05-15',
            posterPath: '/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
            backdropPath: '/tbhdm8UJAb4ViCTsulYFL3lxMCd.jpg',
            rating: 8.1,
            genres: JSON.stringify(['action', 'adventure']),
            director: 'George Miller',
            cast: JSON.stringify(['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne']),
            runtime: 120,
            voteCount: 10230,
            popularity: 115.2,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=hEJnMQG9ev8']),
            aiTags: JSON.stringify(['intense', 'thrilling', 'fun']),
            underrated: false,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            tmdbId: 120467,
            title: 'The Grand Budapest Hotel',
            overview: 'The adventures of Gustave H, a legendary concierge at a famous hotel, and Zero Moustafa, the lobby boy who becomes his most trusted friend. A whimsical tale of friendship and adventure.',
            releaseDate: '2014-03-07',
            posterPath: '/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
            backdropPath: '/tVPRVu0fB6IuEl9G1YkuvYfoet4.jpg',
            rating: 8.1,
            genres: JSON.stringify(['comedy', 'drama']),
            director: 'Wes Anderson',
            cast: JSON.stringify(['Ralph Fiennes', 'Tony Revolori', 'Saoirse Ronan', 'Willem Dafoe']),
            runtime: 99,
            voteCount: 9540,
            popularity: 102.6,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=1Fg5iWmQjwk']),
            aiTags: JSON.stringify(['fun', 'heartwarming', 'uplifting']),
            underrated: false,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            tmdbId: 244786,
            title: 'Whiplash',
            overview: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential. An intense exploration of ambition and abuse.',
            releaseDate: '2014-10-10',
            posterPath: '/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
            backdropPath: '/bP2vGqy81ZydGy2hN7OurezFrxz.jpg',
            rating: 8.5,
            genres: JSON.stringify(['drama', 'music']),
            director: 'Damien Chazelle',
            cast: JSON.stringify(['Miles Teller', 'J.K. Simmons', 'Paul Reiser', 'Melissa Benoist']),
            runtime: 106,
            voteCount: 10670,
            popularity: 108.9,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=7d_jQycdQGo']),
            aiTags: JSON.stringify(['intense', 'thrilling', 'cerebral']),
            underrated: false,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            tmdbId: 545611,
            title: 'Everything Everywhere All at Once',
            overview: 'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save the world by exploring other universes connecting with the lives she could have led. A mind-bending multiverse adventure.',
            releaseDate: '2022-03-25',
            posterPath: '/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
            backdropPath: '/yBth94gHPbPgzZJhbWnWGVcc0hJ.jpg',
            rating: 8.0,
            genres: JSON.stringify(['sci-fi', 'comedy']),
            director: 'Daniels',
            cast: JSON.stringify(['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'Jamie Lee Curtis']),
            runtime: 139,
            voteCount: 11340,
            popularity: 129.3,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=wxN1T1uxQ2g']),
            aiTags: JSON.stringify(['cerebral', 'fun', 'thought-provoking', 'heartwarming']),
            underrated: false,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            tmdbId: 546554,
            title: 'Knives Out',
            overview: 'A detective investigates the death of a patriarch of an eccentric, combative family. A clever modern whodunit with a star-studded ensemble cast.',
            releaseDate: '2019-11-27',
            posterPath: '/pThyQovXQrw2m0s9x82twj48Jq4.jpg',
            backdropPath: '/iGnCzXEx0cFlUbpyAMeHwHWhPhx.jpg',
            rating: 7.9,
            genres: JSON.stringify(['mystery', 'comedy']),
            director: 'Rian Johnson',
            cast: JSON.stringify(['Daniel Craig', 'Ana de Armas', 'Chris Evans', 'Jamie Lee Curtis']),
            runtime: 131,
            voteCount: 9230,
            popularity: 95.7,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=qGqiHJTsRkQ']),
            aiTags: JSON.stringify(['fun', 'thrilling', 'cerebral']),
            underrated: false,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            tmdbId: 503919,
            title: 'The Lighthouse',
            overview: 'Two lighthouse keepers try to maintain their sanity while living on a remote and mysterious New England island in the 1890s. A hypnotic descent into madness.',
            releaseDate: '2019-10-18',
            posterPath: '/3nk9UoepYmv1G9oP18q6JJCeYwN.jpg',
            backdropPath: '/gEYejKvj6iV9OoHhVPz4pUQlqBs.jpg',
            rating: 7.5,
            genres: JSON.stringify(['horror', 'drama']),
            director: 'Robert Eggers',
            cast: JSON.stringify(['Robert Pattinson', 'Willem Dafoe']),
            runtime: 109,
            voteCount: 7840,
            popularity: 68.4,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=Hyag7lR8CPA']),
            aiTags: JSON.stringify(['dark', 'intense', 'cerebral', 'suspenseful']),
            underrated: true,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            tmdbId: 371746,
            title: 'Hunt for the Wilderpeople',
            overview: 'A defiant city kid and his foster uncle become the subjects of a manhunt after they get stranded in the New Zealand wilderness. A heartwarming adventure comedy from New Zealand.',
            releaseDate: '2016-03-31',
            posterPath: '/uMhQ7yROafl0xqL6gx7jKc49ExQ.jpg',
            backdropPath: '/9FQzWCKmhqTEm4qSQxKhSPdlbO4.jpg',
            rating: 7.8,
            genres: JSON.stringify(['comedy', 'adventure']),
            director: 'Taika Waititi',
            cast: JSON.stringify(['Sam Neill', 'Julian Dennison', 'Rima Te Wiata', 'Rachel House']),
            runtime: 101,
            voteCount: 6950,
            popularity: 62.3,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=dPaU4Gymt3E']),
            aiTags: JSON.stringify(['fun', 'heartwarming', 'uplifting']),
            underrated: true,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            tmdbId: 447332,
            title: 'A Quiet Place',
            overview: 'In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing. A tense survival thriller with minimal dialogue.',
            releaseDate: '2018-04-06',
            posterPath: '/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
            backdropPath: '/roYyPiQDQKmIKUEhO912693tSja.jpg',
            rating: 7.5,
            genres: JSON.stringify(['horror', 'thriller']),
            director: 'John Krasinski',
            cast: JSON.stringify(['Emily Blunt', 'John Krasinski', 'Millicent Simmonds', 'Noah Jupe']),
            runtime: 90,
            voteCount: 8560,
            popularity: 87.9,
            trailers: JSON.stringify(['https://www.youtube.com/watch?v=WR7cc5t7tv8']),
            aiTags: JSON.stringify(['suspenseful', 'thrilling', 'intense']),
            underrated: false,
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
    ];

    await db.insert(movies).values(sampleMovies);
    
    console.log('✅ Movies seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});