import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            userId: 1,
            movieId: 3,
            rating: 5,
            title: 'Mind-Bending Masterpiece',
            content: 'Christopher Nolan has crafted one of the most intellectually stimulating films of the 21st century. Inception takes the heist genre and elevates it to profound new heights by exploring the architecture of dreams and the malleability of reality. The visual effects are groundbreaking, particularly the folding city sequences and the zero-gravity hallway fight. Hans Zimmer\'s score perfectly complements the escalating tension. DiCaprio delivers a vulnerable yet determined performance as Cobb, haunted by guilt and grief. The nested dream sequences are brilliantly executed, never losing the audience despite the complexity. The ending leaves you questioning what\'s real, which is exactly what great cinema should do. A film that demands and rewards multiple viewings.',
            spoilers: false,
            likes: 24,
            createdAt: new Date('2024-11-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-15T14:30:00Z').toISOString(),
        },
        {
            userId: 2,
            movieId: 8,
            rating: 5,
            title: 'The Definition of Cinema',
            content: 'Francis Ford Coppola\'s The Godfather stands as the pinnacle of American filmmaking. This is not merely a gangster film—it\'s an operatic exploration of family, loyalty, power, and the American Dream\'s dark underbelly. Brando\'s portrayal of Don Vito Corleone is iconic, bringing both menace and vulnerability to the patriarch. Pacino\'s transformation from reluctant son to ruthless don is one of cinema\'s greatest character arcs. Gordon Willis\'s cinematography creates a world of shadows and secrecy. The pacing is deliberate, allowing scenes to breathe and characters to develop fully. The baptism sequence is a masterclass in parallel editing. Nino Rota\'s score is hauntingly beautiful. Every frame, every line of dialogue, every performance is perfect. This is essential viewing for anyone who claims to love film.',
            spoilers: false,
            likes: 45,
            createdAt: new Date('2024-11-22T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-11-22T16:45:00Z').toISOString(),
        },
        {
            userId: 2,
            movieId: 9,
            rating: 5,
            title: 'A Masterclass in Social Commentary',
            content: 'Bong Joon-ho\'s Parasite is a scathing critique of class inequality wrapped in genre-defying brilliance. The film seamlessly blends dark comedy, thriller, and drama while maintaining a consistent tone of mounting dread. The Kim family\'s infiltration of the Park household is both comedic and unsettling. The production design brilliantly contrasts the semi-basement home with the modernist mansion, making physical space a metaphor for class division. The reveal of the bunker resident completely upends the narrative, introducing another layer to the class hierarchy. The flood sequence devastatingly illustrates how disaster affects classes differently. The final act\'s violence erupts from accumulated resentment and desperation. The ending is intentionally ambiguous—Ki-woo\'s fantasy of wealth feels impossible, highlighting the cycle of poverty. This isn\'t just about Korea; it\'s about global capitalism. A genre-bending masterpiece that will be studied for decades.',
            spoilers: true,
            likes: 38,
            createdAt: new Date('2024-12-01T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-01T11:20:00Z').toISOString(),
        },
        {
            userId: 3,
            movieId: 13,
            rating: 5,
            title: 'Pure Adrenaline!',
            content: 'Mad Max Fury Road is what happens when a visionary director gets complete creative freedom. George Miller delivers a two-hour chase sequence that never lets up. The practical effects are jaw-dropping—real vehicles, real explosions, real stunts. CGI is used sparingly to enhance, not replace. Charlize Theron\'s Furiosa is a badass protagonist fighting for redemption and freedom. Tom Hardy\'s Max is the perfect reluctant hero. The world-building is incredible—you understand this post-apocalyptic society through visuals alone. The War Boys\' cult-like devotion, the grotesque hierarchy, the desperation for resources—it\'s all there. The guitar guy shooting flames is insane and I love it! The color palette of orange desert and blue sky is stunning. The feminism themes are woven naturally into the action. No fat on this film—every second serves the story. This is how you make an action movie. This is cinema at its most primal and exhilarating!',
            spoilers: false,
            likes: 31,
            createdAt: new Date('2024-11-18T19:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-18T19:15:00Z').toISOString(),
        },
        {
            userId: 4,
            movieId: 10,
            rating: 5,
            title: 'Magical and Heartwarming',
            content: 'Spirited Away is Hayao Miyazaki at his finest, creating a world so imaginative and rich that it stays with you long after viewing. Chihiro\'s journey from scared child to brave young woman is beautifully handled. The bathhouse is filled with fascinating creatures and spirits, each with personality. No-Face\'s arc mirrors themes of greed and loneliness. The environmental message about the river spirit is touching without being preachy. Joe Hisaishi\'s score is absolutely magical—it captures wonder, melancholy, and hope perfectly. The hand-drawn animation is breathtaking, with every frame worthy of being art. The silence on the train ride is so peaceful and contemplative. Miyazaki understands that children can handle complex emotions and themes. There\'s no clear villain—even Yubaba has moments of love for her baby. This film reminds us of the importance of remembering who we are, being kind, and working hard. A timeless masterpiece that transcends age and culture.',
            spoilers: false,
            likes: 28,
            createdAt: new Date('2024-11-25T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-11-25T13:40:00Z').toISOString(),
        },
        {
            userId: 5,
            movieId: 18,
            rating: 5,
            title: 'Underrated Psychological Horror Gem',
            content: 'Robert Eggers\' The Lighthouse is a claustrophobic descent into madness that deserves far more recognition. Shot in black and white with a 1.19:1 aspect ratio, the film feels like unearthed footage from another era. The boxy frame traps Willem Dafoe and Robert Pattinson together, creating unbearable tension. Dafoe\'s performance is theatrical and terrifying, delivering archaic dialogue with biblical fury. Pattinson matches him, portraying escalating paranoia masterfully. The sound design is oppressive—the constant fog horn, crashing waves, and screeching gulls create sensory assault. The cinematography by Jarin Blaschke is stunning, using shadows and light to craft nightmarish imagery. The film works as both character study and mythology—the Prometheus parallels, the mermaid symbolism, the obsession with forbidden light. The ambiguity is intentional. Are the supernatural elements real or madness-induced? The final image of Pattinson being consumed by gulls after achieving his goal is perfectly tragic. This is arthouse horror done right—challenging, atmospheric, and unforgettable.',
            spoilers: true,
            likes: 19,
            createdAt: new Date('2024-12-05T20:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-05T20:30:00Z').toISOString(),
        },
        {
            userId: 1,
            movieId: 16,
            rating: 5,
            title: 'Chaotic Perfection',
            content: 'Everything Everywhere All at Once is the most creatively insane film I\'ve seen in years. The Daniels have created something that shouldn\'t work—mixing multiverse sci-fi, martial arts, family drama, absurdist comedy, and existential philosophy—yet it absolutely does. Michelle Yeoh gives the performance of her career as Evelyn, capturing exhaustion, confusion, determination, and love. The film explores generational trauma, immigrant experience, and the weight of unfulfilled potential. Ke Huy Quan\'s return to acting is wonderful—Waymond represents kindness as strength. Stephanie Hsu makes Joy/Jobu both sympathetic and terrifying. The everything bagel as nihilism is genius. The film asks: in infinite universes where nothing matters, what gives life meaning? The answer is beautifully simple—the people we love, the small moments of connection. The hot dog fingers universe is hilarious yet touching. The rocks having a conversation about existence made me cry. This film is messy, overwhelming, and absolutely perfect. It captures what it feels like to be alive right now.',
            spoilers: false,
            likes: 42,
            createdAt: new Date('2024-11-28T10:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-28T10:15:00Z').toISOString(),
        },
        {
            userId: 2,
            movieId: 15,
            rating: 5,
            title: 'Intense Character Study',
            content: 'Damien Chazelle\'s Whiplash is a brutal examination of artistic ambition and abusive mentorship. Miles Teller and J.K. Simmons deliver career-defining performances. Simmons\' Fletcher is terrifying—a conductor who weaponizes humiliation and psychological torture in pursuit of greatness. The film asks uncomfortable questions: Does greatness require suffering? Can abuse be justified if it produces genius? Teller\'s Andrew is equally obsessed, willing to destroy his body and relationships for drumming perfection. The editing, particularly during performance sequences, is breathless and anxiety-inducing. The final performance is cathartic yet disturbing—Andrew achieves his moment of transcendence, but at what cost? Has he won or has Fletcher? The ambiguous ending deliberately refuses easy answers. The film\'s jazz setting is perfect—an art form built on improvisation and discipline. The blood on the drums, the thrown chair, the car crash—everything escalates to painful extremes. This is uncomfortable, thrilling cinema that doesn\'t let you look away.',
            spoilers: false,
            likes: 33,
            createdAt: new Date('2024-12-03T15:50:00Z').toISOString(),
            updatedAt: new Date('2024-12-03T15:50:00Z').toISOString(),
        },
        {
            userId: 3,
            movieId: 2,
            rating: 5,
            title: 'Best Superhero Movie Ever',
            content: 'Christopher Nolan elevated superhero cinema to new heights with The Dark Knight. This isn\'t just a great comic book movie—it\'s a great crime thriller that happens to feature Batman. Heath Ledger\'s Joker is legendary. He transformed the character into an agent of chaos, delivering a performance that\'s terrifying, unpredictable, and mesmerizing. Every scene he\'s in crackles with tension. Christian Bale brings depth to Bruce Wayne, showing the toll of being Batman. Aaron Eckhart\'s Harvey Dent/Two-Face arc is tragic and compelling. The action sequences are phenomenal—the truck flip, the hospital explosion, the final showdown. The ferry experiment brilliantly explores moral philosophy under pressure. The film examines heroism, sacrifice, and the fine line between hero and vigilante. The ending is perfect—Batman takes the fall to preserve hope, becoming the Dark Knight. Hans Zimmer\'s score is epic. The IMAX cinematography is stunning. This is the benchmark that all superhero films are measured against, and most fall short.',
            spoilers: false,
            likes: 56,
            createdAt: new Date('2024-11-20T17:25:00Z').toISOString(),
            updatedAt: new Date('2024-11-20T17:25:00Z').toISOString(),
        },
        {
            userId: 5,
            movieId: 19,
            rating: 4,
            title: 'Charming Hidden Gem from New Zealand',
            content: 'Hunt for the Wilderpeople is a delightful adventure comedy that deserves more attention. Taika Waititi brings his signature humor and heart to this story of a rebellious foster kid and his grumpy foster uncle on the run in the New Zealand bush. Julian Dennison is wonderful as Ricky Baker—defiant yet vulnerable, funny yet genuine. Sam Neill gives one of his best performances as Uncle Hec, gradually warming to his unlikely companion. Their relationship develops naturally, with humor masking deeper emotions. The film balances comedy with touching moments about family, belonging, and healing from trauma. The bush setting is gorgeous, showcasing New Zealand\'s stunning landscapes. Paula, the child services officer, is a hilarious antagonist. The film references everything from Rambo to Lord of the Rings while maintaining its own identity. The humor is quirky without being forced. My only minor complaint is the pacing drags slightly in the middle, hence four stars instead of five. Still, this is a charming, funny, and heartfelt film that leaves you smiling.',
            spoilers: false,
            likes: 15,
            createdAt: new Date('2024-12-08T12:10:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T12:10:00Z').toISOString(),
        },
        {
            userId: 1,
            movieId: 5,
            rating: 5,
            title: 'Timeless Classic',
            content: 'Forrest Gump is a film that defines a generation. Robert Zemeckis weaves American history through the eyes of a simple man with a pure heart, creating something magical. Tom Hanks gives one of his most iconic performances—Forrest is innocent without being simple, kind without being naive. His unwavering love for Jenny is both beautiful and heartbreaking. The film\'s structure, jumping through decades of American history, never feels gimmicky. Watching Forrest inadvertently influence major events is clever and entertaining. The special effects integrating Forrest into historical footage were groundbreaking. Gary Sinise as Lieutenant Dan provides emotional weight, his character arc paralleling America\'s struggle with Vietnam. The "Run, Forrest, run!" scenes capture pure freedom and determination. Alan Silvestri\'s score is perfect—sweeping and emotional without being manipulative. The film explores themes of destiny versus chance, love and loss, the American Dream. It makes you laugh and cry, often in the same scene. A perfect film that holds up decades later.',
            spoilers: false,
            likes: 29,
            createdAt: new Date('2024-11-12T09:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-12T09:30:00Z').toISOString(),
        },
        {
            userId: 2,
            movieId: 11,
            rating: 4,
            title: 'Chilling Performances',
            content: 'Jonathan Demme\'s The Silence of the Lambs is a masterclass in psychological thriller filmmaking. Anthony Hopkins creates one of cinema\'s most iconic villains despite being onscreen for only 16 minutes. His Hannibal Lecter is sophisticated, terrifying, and strangely sympathetic. The chemistry between Hopkins and Jodie Foster is electric—their conversations are tense verbal sparring matches. Foster\'s Clarice Starling is a strong, intelligent protagonist navigating a male-dominated FBI while confronting her own trauma. The film explores power dynamics, gender politics, and the nature of evil. Ted Levine\'s Buffalo Bill is genuinely disturbing. The night vision basement sequence is one of the most suspenseful scenes in cinema. The film\'s pacing is deliberate, building dread methodically. My only minor criticism is that some dated elements prevent it from being perfect—hence four stars. The moth symbolism is heavy-handed at times. However, the performances elevate everything. The final phone call between Hannibal and Clarice is perfectly unsettling. A landmark thriller that influenced countless films.',
            spoilers: true,
            likes: 27,
            createdAt: new Date('2024-12-10T18:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T18:45:00Z').toISOString(),
        },
        {
            userId: 4,
            movieId: 14,
            rating: 5,
            title: 'Whimsical and Beautiful',
            content: 'The Grand Budapest Hotel is Wes Anderson at his most Wes Anderson, and it\'s glorious. The film is a meticulously crafted confection, with every frame composed like a painting. The symmetrical shots, pastel color palette, and miniature effects create a storybook aesthetic. Ralph Fiennes gives a career-best performance as Gustave H., the fastidious concierge with a golden heart and questionable morals. His relationship with Zero is the emotional core—mentor and protégé becoming family. The ensemble cast is perfect, with each actor committing fully to Anderson\'s stylized world. The story-within-a-story-within-a-story structure adds layers of nostalgia and melancholy. Beneath the whimsy lies commentary on war, fascism, and the death of European elegance. The chase sequence is hilarious, combining slapstick with Anderson\'s precise visual style. Alexandre Desplat\'s score enhances the fairy tale atmosphere. The film celebrates art, culture, and civilization while acknowledging their fragility. Every detail is intentional, from costume design to typography. This is pure cinema—beautiful, funny, moving, and unforgettable.',
            spoilers: false,
            likes: 22,
            createdAt: new Date('2024-11-30T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-11-30T14:20:00Z').toISOString(),
        },
        {
            userId: 3,
            movieId: 7,
            rating: 5,
            title: 'Epic Space Adventure',
            content: 'Christopher Nolan\'s Interstellar is a monumental achievement in science fiction cinema. The film balances hard sci-fi concepts with deep emotional resonance. Matthew McConaughey delivers a heartfelt performance as Cooper, a father willing to sacrifice everything for humanity\'s survival. The father-daughter relationship is the emotional anchor—the scene where Cooper watches decades of messages from his children is devastating. The visuals are breathtaking, from the wormhole to the black hole Gargantua, which was scientifically accurate enough to result in academic papers. The scale is immense—you feel the vastness of space and time. Hans Zimmer\'s organ-heavy score is powerful and otherworldly. The Tesseract sequence is mind-bending, visualizing love as a dimension that transcends space and time. Anne Hathaway\'s "love is the one thing we\'re capable of perceiving that transcends dimensions" speech is surprisingly moving. The film explores survival, sacrifice, and the bonds that connect us across impossible distances. Yes, the ending requires suspension of disbelief, but the emotional payoff is worth it. A stunning, ambitious film.',
            spoilers: false,
            likes: 48,
            createdAt: new Date('2024-11-17T16:00:00Z').toISOString(),
            updatedAt: new Date('2024-11-17T16:00:00Z').toISOString(),
        },
        {
            userId: 5,
            movieId: 17,
            rating: 4,
            title: 'Smart Modern Whodunit',
            content: 'Rian Johnson\'s Knives Out breathes fresh life into the murder mystery genre. This is an Agatha Christie-style whodunit for the modern age, complete with social commentary and a fantastic ensemble cast. Daniel Craig clearly has fun playing Benoit Blanc, a detective with a ridiculous accent and sharp mind. Ana de Armas is wonderful as Marta—her inability to lie and genuine goodness make her the perfect protagonist. The Thrombey family is a delicious collection of entitled, selfish people, each with motive and opportunity. The film\'s structure is clever, revealing the "how" early then focusing on the "why" and "who else." The class commentary is sharp—contrasting the wealthy family\'s casual cruelty with Marta\'s immigrant family\'s genuine warmth. The production design gives each character distinct spaces reflecting their personalities. The film is funny without sacrificing tension. My only critique keeping it from five stars is that the final act\'s resolution feels slightly rushed. Still, this is a supremely entertaining mystery with replay value. You notice new clues and jokes with each viewing.',
            spoilers: false,
            likes: 25,
            createdAt: new Date('2024-12-06T11:35:00Z').toISOString(),
            updatedAt: new Date('2024-12-06T11:35:00Z').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});